// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// puny_encode_cpp
Rcpp::CharacterVector puny_encode_cpp(Rcpp::CharacterVector domains, bool strict);
RcppExport SEXP _punycoder_puny_encode_cpp(SEXP domainsSEXP, SEXP strictSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type domains(domainsSEXP);
    Rcpp::traits::input_parameter< bool >::type strict(strictSEXP);
    rcpp_result_gen = Rcpp::wrap(puny_encode_cpp(domains, strict));
    return rcpp_result_gen;
END_RCPP
}
// puny_decode_cpp
Rcpp::CharacterVector puny_decode_cpp(Rcpp::CharacterVector domains, bool strict);
RcppExport SEXP _punycoder_puny_decode_cpp(SEXP domainsSEXP, SEXP strictSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type domains(domainsSEXP);
    Rcpp::traits::input_parameter< bool >::type strict(strictSEXP);
    rcpp_result_gen = Rcpp::wrap(puny_decode_cpp(domains, strict));
    return rcpp_result_gen;
END_RCPP
}
// validate_domain_cpp
Rcpp::List validate_domain_cpp(Rcpp::CharacterVector domains, bool strict);
RcppExport SEXP _punycoder_validate_domain_cpp(SEXP domainsSEXP, SEXP strictSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type domains(domainsSEXP);
    Rcpp::traits::input_parameter< bool >::type strict(strictSEXP);
    rcpp_result_gen = Rcpp::wrap(validate_domain_cpp(domains, strict));
    return rcpp_result_gen;
END_RCPP
}
// backend_info_cpp
Rcpp::List backend_info_cpp();
RcppExport SEXP _punycoder_backend_info_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(backend_info_cpp());
    return rcpp_result_gen;
END_RCPP
}
// compare_backends_cpp
Rcpp::List compare_backends_cpp(Rcpp::CharacterVector input, std::string mode, bool strict);
RcppExport SEXP _punycoder_compare_backends_cpp(SEXP inputSEXP, SEXP modeSEXP, SEXP strictSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type input(inputSEXP);
    Rcpp::traits::input_parameter< std::string >::type mode(modeSEXP);
    Rcpp::traits::input_parameter< bool >::type strict(strictSEXP);
    rcpp_result_gen = Rcpp::wrap(compare_backends_cpp(input, mode, strict));
    return rcpp_result_gen;
END_RCPP
}
// host_normalize_cpp
Rcpp::CharacterVector host_normalize_cpp(Rcpp::CharacterVector x, std::string unicode_version, bool check_hyphens, bool use_std3, bool verify_dns_length);
RcppExport SEXP _punycoder_host_normalize_cpp(SEXP xSEXP, SEXP unicode_versionSEXP, SEXP check_hyphensSEXP, SEXP use_std3SEXP, SEXP verify_dns_lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type unicode_version(unicode_versionSEXP);
    Rcpp::traits::input_parameter< bool >::type check_hyphens(check_hyphensSEXP);
    Rcpp::traits::input_parameter< bool >::type use_std3(use_std3SEXP);
    Rcpp::traits::input_parameter< bool >::type verify_dns_length(verify_dns_lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(host_normalize_cpp(x, unicode_version, check_hyphens, use_std3, verify_dns_length));
    return rcpp_result_gen;
END_RCPP
}
// normalization_unicode_version_cpp
std::string normalization_unicode_version_cpp();
RcppExport SEXP _punycoder_normalization_unicode_version_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(normalization_unicode_version_cpp());
    return rcpp_result_gen;
END_RCPP
}
// unicode_versions_cpp
Rcpp::List unicode_versions_cpp();
RcppExport SEXP _punycoder_unicode_versions_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(unicode_versions_cpp());
    return rcpp_result_gen;
END_RCPP
}
