// Generated by data-raw/generate_unicode_tables.R. DO NOT EDIT BY HAND.
// Unicode 17.0.0. Accessors for NFC + UTS-46 used by canonical-host normalization.
#ifndef PUNYCODER_UNICODE_TABLES_17_0_0_H
#define PUNYCODER_UNICODE_TABLES_17_0_0_H

#include <cstddef>
#include <cstdint>

namespace punycoder {
namespace u17 {

extern const char *const UNICODE_VERSION;

enum class IdnaStatus : uint8_t {
  valid = 0,
  ignored = 1,
  mapped = 2,
  deviation = 3,
  disallowed = 4,
  disallowed_std3_valid = 5,
  disallowed_std3_mapped = 6
};

// Canonical combining class of cp (0 if unlisted).
uint8_t combining_class(uint32_t cp);

// Full canonical decomposition of cp (recursively expanded, excluding Hangul).
// Returns a pointer to len code points, or nullptr with len = 0 if none.
const uint32_t *canonical_decomposition(uint32_t cp, uint32_t &len);

// Primary canonical composition of starter a and combiner b; 0 if none.
uint32_t canonical_compose(uint32_t a, uint32_t b);

// True if b can be the SECOND element of some canonical composition pair.
// This is the bound canonical_compose() applies before anything else, exposed
// here so a caller can apply it BEFORE the call rather than after: b is always
// a combining character, so ordinary text answers it without touching memory,
// and at that point the call itself is the whole cost. Both bounds are derived
// from the pair table like every other constant in this file (ADR-011).
inline bool composes_as_second(uint32_t b) {
  return b >= 0x300 && b <= 0x16D67;
}

// NFC_Quick_Check (UAX #15). `maybe` means the character MAY compose with
// what precedes it, so it is not a weaker `no` -- a caller that folds it into
// `yes` is wrong on exactly the input a quick check exists to detect.
enum class NfcQuickCheck : uint8_t { yes = 0, no = 1, maybe = 2 };
NfcQuickCheck nfc_quick_check(uint32_t cp);

// True if cp can play no part in whether a sequence is in NFC: every code
// point below this bound has combining class 0 and NFC_Quick_Check=Yes, so a
// run of them is already normalized. Inline because the check that uses it
// runs once per character and this answers all of ASCII without a call, let
// alone a table read. The bound is the lower of the two tables' first listed
// code point, derived like every other constant here (ADR-011).
inline bool nfc_inert(uint32_t cp) { return cp < 0x300; }

// UTS-46 status of cp. If the status is mapped, deviation, or
// disallowed_std3_mapped and a mapping exists, sets map/len to the target
// sequence (len may be 0 for an empty mapping). Unlisted code points are
// disallowed.
IdnaStatus idna_lookup(uint32_t cp, const uint32_t *&map, uint32_t &len);

// True if cp has general category Mn, Mc, or Me (UTS-46 rule V5).
bool is_combining_mark(uint32_t cp);

// Bidi_Class of cp (RFC 5893 CheckBidi). Unlisted code points return L; they
// are disallowed by UTS-46 mapping and never reach CheckBidi.
enum class BidiClass : uint8_t {
  L = 0, R, AL, AN, EN, ES, ET, CS, NSM, BN, B, S, WS, ON,
  LRE, LRO, RLE, RLO, PDF, LRI, RLI, FSI, PDI
};
BidiClass bidi_class(uint32_t cp);

// Joining_Type of cp (IDNA2008 ContextJ CheckJoiners). Unlisted code points
// return U (Non_Joining), the property default.
enum class JoiningType : uint8_t { U = 0, C, D, L, R, T };
JoiningType joining_type(uint32_t cp);

// A version-agnostic handle on this table set, for pipeline code templated on
// the table unit. Members forward to the accessors above and alias this
// namespace's enums; all are implicitly inline, so the indirection is a
// compile-time one only.
struct Tables {
  typedef ::punycoder::u17::IdnaStatus IdnaStatus;
  typedef ::punycoder::u17::NfcQuickCheck NfcQuickCheck;
  typedef ::punycoder::u17::BidiClass BidiClass;
  typedef ::punycoder::u17::JoiningType JoiningType;

  static const char *version() { return ::punycoder::u17::UNICODE_VERSION; }

  static uint8_t combining_class(uint32_t cp) {
    return ::punycoder::u17::combining_class(cp);
  }
  static const uint32_t *canonical_decomposition(uint32_t cp, uint32_t &len) {
    return ::punycoder::u17::canonical_decomposition(cp, len);
  }
  static uint32_t canonical_compose(uint32_t a, uint32_t b) {
    return ::punycoder::u17::canonical_compose(a, b);
  }
  static bool composes_as_second(uint32_t b) {
    return ::punycoder::u17::composes_as_second(b);
  }
  static NfcQuickCheck nfc_quick_check(uint32_t cp) {
    return ::punycoder::u17::nfc_quick_check(cp);
  }
  static bool nfc_inert(uint32_t cp) {
    return ::punycoder::u17::nfc_inert(cp);
  }
  static IdnaStatus idna_lookup(uint32_t cp, const uint32_t *&map,
                                uint32_t &len) {
    return ::punycoder::u17::idna_lookup(cp, map, len);
  }
  static bool is_combining_mark(uint32_t cp) {
    return ::punycoder::u17::is_combining_mark(cp);
  }
  static BidiClass bidi_class(uint32_t cp) {
    return ::punycoder::u17::bidi_class(cp);
  }
  static JoiningType joining_type(uint32_t cp) {
    return ::punycoder::u17::joining_type(cp);
  }
};

}  // namespace u17
}  // namespace punycoder

#endif  // PUNYCODER_UNICODE_TABLES_17_0_0_H

